
spring.datasource.url: jdbc:mysql://localhost:3306/blog
#spring.datasource.url: jdbc:mysql://localhost:3306/blog?useSSL=false&amp;serverTimezone=UTC
#spring.datasource.url: jdbc:mysql://localhost:3306/deals?useSSL=false&amp;serverTimezone=UTC

spring.datasource.username: root
spring.datasource.password: 123456789
#spring.jpa.hibernate.ddl-auto: none
#spring.jpa.hibernate.ddl-auto: create
spring.jpa.hibernate.ddl-auto: validate
#spring.jpa.hibernate.ddl-auto: update
#spring.jpa.show-sql: false
spring.jpa.show-sql: true

spring.flyway.user: root
spring.flyway.password: 123456789
spring.flyway.schemas: blog

spring.flyway.enabled: true
spring.flyway.group: true
#spring.flyway.enabled: false

#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +79021111111
#blog.email: mail@mail.ru
blog.email: borisov_skillbox@mail.ru
blog.emailPass: Skill-box
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005


#blog.title=DevPub
#blog.subtitle=Рассказы разработчиков
#blog.phone=+79021111111


someParameter:
  value: Успехов в реализации планов!!!!!!!!!!
  uploadFld: D:\Skill\IdeaProjects\BlogEngine\src\main\resources\static\
  dstFolder: upload/profileImages
