
spring.datasource.url: jdbc:mysql://localhost:3306/blog
#spring.datasource.url: jdbc:mysql://localhost:3306/blog?useSSL=false&amp;serverTimezone=UTC
#spring.datasource.url: jdbc:mysql://localhost:3306/deals?useSSL=false&amp;serverTimezone=UTC

spring.datasource.username: root
spring.datasource.password: 123456789
#spring.jpa.hibernate.ddl-auto: none
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: false

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +79021111111
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005


#blog.title=DevPub
#blog.subtitle=Рассказы разработчиков
#blog.phone=+79021111111


someParameter:
  value: Успехов в реализации планов!!!!!!!!!!